### ISSUE TITLE
can this bundle work with Symfony3?

### ISSUE THREAD

**Issue by alvinbunk** [GeniusesOfSymfony/PubSubRouterBundle#15]
I've tried installing via Symfony3 using:
composer require gos/pubsub-router-bundle
and then registered in AppKernel.php; however, i get the error messages (clearing cache):

PHP Fatal error:  Uncaught InvalidArgumentException: Bundle "pubsub" does not exist or it is not enabled. Maybe you forgot to add it in the registerBundles() method of your AppKernel.php file? in /var/www/html/socket/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:198
Stack trace:
#0 /var/www/html/socket/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(232): Symfony\Component\HttpKernel\Kernel->getBundle('pubsub', false)
#1 /var/www/html/socket/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Config/FileLocator.php(51): Symfony\Component\HttpKernel\Kernel->locateResource('@pubsub/routing...', '/var/www/html/s...', true)
#2 /var/www/html/socket/vendor/gos/pubsub-router-bundle/Loader/AbstractRouteLoader.php(20): Symfony\Component\HttpKernel\Config\FileLocator->locate('@pubsub/routing...')
#3 /var/www/html/socket/vendor/gos/pubsub-router-bundle/Loader/YamlFileLoader.php(34): Gos\Bundle\PubSubRouterBundle\Loader\AbstractRouteLoader->load('@pubsub/routing...', NULL)
#4 /var/www/html/socke in /var/www/html/socket/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php on line 198

I'm also trying to mainly get the WebSocketBundle to work, and I believe this is a install requirement, but yet it is not mentioned in the WebSocketBundle documentation.

**Comment by mbabker** [comment]
Rather old issue but bundle supports Symfony 3.4+ as of now.
