### ISSUE TITLE
PHP 5.4?

### ISSUE THREAD

**Issue by kachkaev** [GeniusesOfSymfony/PubSubRouterBundle#3]
The bundle's composer.json says that the code only works in PHP 5.5+. Is this really the case that it cannot be ran on 5.4 for some objective reason? Not much changed between these versions, if I am not wrong.

It would be good if you changed composer.json to support PHP 5.4 (if that wont break anything, of course).

**Comment by kachkaev** [comment]
Ugh. Now I see there are things like ``RouterContext::CLASS` that will not work in 5.4. Any chance for a workaround? PHP 5.4 still seems to be a pretty commonly used version.

**Comment by jjsaunier** [comment]
Yes it possible to downgrade on php5.4 ofc, I don't use advanced feature, only `::class` so it ridiculous to keep 5.5 as minimum version for that.

Feel free to send PR.
